//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyAnalysis2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimate
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int PeroidId { get; set; }
        public int UserId { get; set; }
        public double Revenue { get; set; }
        public double NetIncome { get; set; }
        public double Assets { get; set; }
        public double Equity { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual User User { get; set; }
        public virtual Company Company { get; set; }
    }
}
