//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyAnalysis2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialIndicator
    {
        public int Id { get; set; }
        public int PeriodId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<double> ProfitMargin { get; set; }
        public Nullable<double> Solidity { get; set; }
        public Nullable<double> NetIncomeTTM { get; set; }
        public Nullable<double> RevenueTTM { get; set; }
        public Nullable<double> ProfitMarginTTM { get; set; }
        public Nullable<double> PeTTM { get; set; }
        public Nullable<double> ReturnOnAssetsTTM { get; set; }
        public Nullable<double> ReturnOnEquityTTM { get; set; }
        public Nullable<double> InvestmentGradeTTM { get; set; }
        public Nullable<double> EqutiyGrowthTTM { get; set; }
        public Nullable<double> NetIncomeGrowthTTM { get; set; }
        public Nullable<double> RevenueGrowthTTM { get; set; }
        public Nullable<double> Revenue { get; set; }
        public Nullable<double> NetIncome { get; set; }
        public Nullable<double> Assets { get; set; }
        public Nullable<double> Equity { get; set; }
        public Nullable<double> MarketCap { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Period Period { get; set; }
    }
}
