//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyAnalysis2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialIndicator
    {
        public int Id { get; set; }
        public int PeriodId { get; set; }
        public int CompanyId { get; set; }
        public double Revenue { get; set; }
        public double NetIncome { get; set; }
        public double Assets { get; set; }
        public double Equity { get; set; }
        public double ProfitMargin { get; set; }
        public double Solidity { get; set; }
        public double NetIncomeTTM { get; set; }
        public double RevenueTTM { get; set; }
        public double ProfitMarginTTM { get; set; }
        public double PeTTM { get; set; }
        public double ReturnOnAssetsTTM { get; set; }
        public double ReturnOnEquityTTM { get; set; }
        public double EqutiyGrowthTTM { get; set; }
        public double NetIncomeGrowthTTM { get; set; }
        public double RevenueGrowthTTM { get; set; }
        public double InvestmentGradeTTM { get; set; }
        public double MarketCap { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Company Company { get; set; }
    }
}
