//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyAnalysis2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<double> Revenue { get; set; }
        public Nullable<double> NetIncome { get; set; }
        public Nullable<double> Assets { get; set; }
        public Nullable<double> Equity { get; set; }
        public string CEO { get; set; }
        public bool Overwrite { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Period Period { get; set; }
        public virtual User CreatedBy { get; set; }
    }
}
