//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyAnalysis2.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StockQuote
    {
        [Key]
        public System.DateTime Date { get; set; }
        [Key]
        public int StockId { get; set; }
        public double Price { get; set; }
        public Nullable<long> NumberOfSharesOutstanding { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
