//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyAnalysis2.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserSetting
    {
        [Key]
        public int UserId { get; set; }
        [Key]
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual User User { get; set; }
    }
}
